### ISSUE TITLE
对第二次握手进行混淆

### ISSUE THREAD

**Issue by beerhall** [warriorpaw/z-ssl-proxy#2]
我看了那个博客，虽然TLS over TLS是可以被检测到的，但是这是基于对第二次握手数据包长度的检测。那个博主在第二次握手时填充了一些无关数据，就成功骗过了GFW。

**Comment by warriorpaw** [comment]
https://github.com/warriorpaw/z-ssl-proxy/tree/mix_up_dev
曾经尝试过，混淆长度。当时结果好像是不太好把。细节忘记了。
